export const publications = [
  {
    title: "DEHB ve Kendine Şefkat",
    description: "DEHB tanısı almış bireylerin kendine şefkat pratikleri üzerine kapsamlı rehber.",
    type: "Kitap",
    year: "2024",
    topics: ["DEHB", "Psikoloji", "Kendine Şefkat"],
    link: "https://example.com/dehb-kendine-sefkat",
  },
  {
    title: "Regülasyon Stratejileri",
    description: "Duygusal regülasyon için pratik teknikler ve uygulanabilir protokoller.",
    type: "Makale",
    year: "2024",
    topics: ["Regülasyon", "Duygusal Zeka", "Terapi"],
    link: "https://example.com/regulasyon-stratejileri",
  },
  {
    title: "İlişkiler ve DEHB",
    description: "DEHB'nin ilişkiler üzerindeki etkisi ve sağlıklı iletişim stratejileri.",
    type: "Makale",
    year: "2023",
    topics: ["İlişkiler", "İletişim", "DEHB"],
    link: "https://example.com/iliskiler-dehb",
  },
  {
    title: "Klinik Deneyimler",
    description: "15 yıllık klinik deneyimden seçilmiş vaka çalışmaları ve çözüm yöntemleri.",
    type: "Kitap",
    year: "2023",
    topics: ["Klinik", "Vaka Çalışması", "Terapi"],
    link: "https://example.com/klinik-deneyimler",
  },
  {
    title: "Mindfulness ve DEHB",
    description: "Meditasyon ve mindfulness pratikleri DEHB yönetiminde nasıl etkili olabilir?",
    type: "Makale",
    year: "2024",
    topics: ["Mindfulness", "Meditasyon", "DEHB"],
    link: "https://example.com/mindfulness-dehb",
  },
  {
    title: "Aile Dinamikleri",
    description: "DEHB'li bireylerin bulunduğu ailelerde sağlıklı dinamikler oluşturma.",
    type: "Makale",
    year: "2023",
    topics: ["Aile", "Dinamikler", "Psikoloji"],
    link: "https://example.com/aile-dinamikleri",
  },
]
